name: expense_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.4.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  sqflite: ^2.1.1
  path: any
  http: ^0.13.3
  fluttertoast: ^8.0.8
  path_provider: ^2.0.14
  connectivity_plus: ^6.0.3
  syncfusion_flutter_charts: ^26.1.38
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  google_sign_in: ^6.2.1
  introduction_screen: ^3.1.8 
  shared_preferences: ^2.0.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
