name: expense_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  cupertino_icons: ^1.0.6
  sqflite: ^2.1.1
  path_provider: ^2.0.14
  syncfusion_flutter_charts: ^26.1.38
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
