// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn31KzNL_QOegq8ewv0WPyoRIsuc4Oajo',
    appId: '1:471151829832:web:4aa8daae1fbb797363c97d',
    messagingSenderId: '471151829832',
    projectId: 'pennywise-d3eae',
    authDomain: 'pennywise-d3eae.firebaseapp.com',
    storageBucket: 'pennywise-d3eae.appspot.com',
    measurementId: 'G-917877BB2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk-6iEL1RdEhwHfqJHfdE7cFgkUGkdTPk',
    appId: '1:471151829832:android:2ba4d8c3110ef63b63c97d',
    messagingSenderId: '471151829832',
    projectId: 'pennywise-d3eae',
    storageBucket: 'pennywise-d3eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHeKJah0Ln6qeWwSFkzJtZ4zcvQVr3FE',
    appId: '1:471151829832:ios:07d7bc11d7c1235263c97d',
    messagingSenderId: '471151829832',
    projectId: 'pennywise-d3eae',
    storageBucket: 'pennywise-d3eae.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUHeKJah0Ln6qeWwSFkzJtZ4zcvQVr3FE',
    appId: '1:471151829832:ios:07d7bc11d7c1235263c97d',
    messagingSenderId: '471151829832',
    projectId: 'pennywise-d3eae',
    storageBucket: 'pennywise-d3eae.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn31KzNL_QOegq8ewv0WPyoRIsuc4Oajo',
    appId: '1:471151829832:web:bbf6cc492974e85663c97d',
    messagingSenderId: '471151829832',
    projectId: 'pennywise-d3eae',
    authDomain: 'pennywise-d3eae.firebaseapp.com',
    storageBucket: 'pennywise-d3eae.appspot.com',
    measurementId: 'G-PT0M5NKWG0',
  );
}
